server:
  port: 9192
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      payment:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 3
        slidingWindowType: COUNT_BASED
